main/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.urls import path
from photoalbum import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('register', views.AddUserView.as_view(), name='register'),
    path('add_photo', views.PhotoUploadView.as_view(), name='add_photo'),
    path('delete_photo/<pk>',
         views.PhotoDeleteView.as_view(),
         name='delete_photo'),
    path('photo_detail/<pk>',
         views.PhotoDetailView.as_view(),
         name='photo_detail'),
    path('my_profile', views.MyProfileView.as_view(), name='profile'),
    path('update_photo/<pk>',
         views.PhotoUpdateView.as_view(),
         name='update_photo'),
    path('reset_password/<id>',
         views.ResetPasswordView.as_view(),
         name='reset_password'),
    path('delete_user/<pk>',
         views.UserDeleteView.as_view(),
         name='delete_user'),
    path('like_photo', views.like_photo, name='like_photo'),
    path('delete_comment/<pk>',
         views.CommentDeleteView.as_view(),
         name='delete_comment'),
    path('update_comment/<pk>',
         views.CommentUpdateView.as_view(),
         name='update_comment'),
] + staticfiles_urlpatterns() + \
  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photoalbum/models.py
from django.db import models
from django.contrib.auth import get_user_model
# from easy_thumbnails.alias import aliases
from easy_thumbnails.signals import saved_file
from easy_thumbnails.signal_handlers import generate_aliases_global

saved_file.connect(generate_aliases_global)

# Create your models here.

# if not aliases.get('photoalbum'):
#     aliases.set('photoalbum', {'size': (500, 250), 'crop': True})

User = get_user_model()


def user_directory(instance, filename):
    return 'user_{}/{}'.format(instance.user.id, filename)


class Photo(models.Model):
    title = models.CharField(max_length=64,
                             verbose_name='Tytuł',
                             null=True,
                             blank=True)
    path = models.ImageField(upload_to=user_directory, verbose_name='Zdjęcie')
    creation_date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             verbose_name="Użytkownik")


class Like(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.CharField(max_length=500, verbose_name="Komentarz")
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             verbose_name="Użytkownik")
    date = models.DateTimeField(auto_now_add=True)
    photo = models.ForeignKey(Photo,
                              on_delete=models.CASCADE,
                              verbose_name="Zdjęcie")

photoalbum/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Photo, Comment
from django.core.validators import EmailValidator
from .validators import validate_login


class LoginForm(forms.Form):
    login = forms.CharField(label='login', max_length=64)
    password = forms.CharField(label='hasło',
                               max_length=64,
                               widget=forms.PasswordInput)


class AddUserForm(forms.Form):
    login = forms.EmailField(label='Login(email)',
                             validators=[EmailValidator, validate_login])
    password = forms.CharField(max_length=64,
                               label='Hasło',
                               widget=forms.PasswordInput)
    password_repeat = forms.CharField(max_length=64,
                                      label='Powtórz hasło',
                                      widget=forms.PasswordInput)

    def clean(self):
        if (self.cleaned_data['password'] is not
                self.cleaned_data['password_repeat']):
            raise ValidationError('Niepoprawne hasło')


class PhotoUploadForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = forms.ALL_FIELDS
        widgets = {'user': forms.HiddenInput}


class PhotoUpdateForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['title']


class ResetPasswordForm(forms.Form):
    new_pass = forms.CharField(label='Wprowadź nowe hasło',
                               max_length=64,
                               widget=forms.PasswordInput)
    new_pass_confirm = forms.CharField(label='Ponownie wprowadź nowe hasło',
                                       max_length=64,
                                       widget=forms.PasswordInput)

    def clean(self):
        if (self.cleaned_data['new_pass'] is not
                self.cleaned_data['new_pass_confirm']):
            raise ValidationError('Niepoprawne hasło')


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {'content': forms.Textarea(attrs={'cols': 40, 'rows': 3})}

photoalbum/views.py
import json

from django.contrib.auth.mixins import (PermissionRequiredMixin,
                                        LoginRequiredMixin)
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.views import View
from django.views.generic import DeleteView, UpdateView
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy, reverse
from .models import User, Photo, Like, Comment
from django.forms.models import modelform_factory
from django import forms

from photoalbum.forms import (LoginForm,
                              AddUserForm,
                              PhotoUploadForm,
                              PhotoUpdateForm,
                              ResetPasswordForm,
                              AddCommentForm)


class IndexView(LoginRequiredMixin, View):
    login_url = 'login'

    def get(self, request):
        all_photo = Photo.objects.order_by('creation_date')
        likes = Like.objects.filter(user=request.user)
        likes_list = list()
        for like in likes:
            likes_list.append(like.photo_id)
        ctx = {'photos': all_photo,
               'likes': likes_list,
               }
        return TemplateResponse(request, 'photoalbum/index.html', ctx)


class LoginView(View):

    def get(self, request):
        return TemplateResponse(request,
                                'photoalbum/login.html',
                                {'form': LoginForm()})

    def post(self, request):
        form = LoginForm(request.POST)
        ctx = {'form': form, 'message': None}
        if form.is_valid():
            username = form.cleaned_data['login']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                ctx.update({'message': 'Błąd loginu lub hasła'})
        return TemplateResponse(request, 'photoalbum/login.html', ctx)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('index')


class AddUserView(View):

    def get(self, request):
        form = AddUserForm()
        return TemplateResponse(request,
                                'photoalbum/user_form.html',
                                {'form': form})

    def post(self, request):
        form = AddUserForm(request.POST)
        ctx = {'form': form}
        if form.is_valid():
            email = form.cleaned_data['login']
            password = form.cleaned_data['password']
            new_user = User.objects.create_user(username=email,
                                                email=email,
                                                password=password)
            login(request, new_user)
            return redirect('index')
        return TemplateResponse(request, 'photoalbum/user_form.html', ctx)


class PhotoUploadView(View):
    template_name = 'photoalbum/photo_form.html'

    def get(self, request):
        user = User.objects.get(id=request.user.id)
        form = PhotoUploadForm(initial={'user': user})
        return TemplateResponse(request, self.template_name, {'form': form})

    def post(self, request):
        form = PhotoUploadForm(request.POST, request.FILES)
        ctx = {'form': form}
        if form.is_valid():
            form.save()
            return redirect('index')
        return TemplateResponse(request, self.template_name, ctx)


class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = reverse_lazy('profile')


class UserDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'auth.delete_user'
    model = User
    template_name = 'photoalbum/user_confirm_delete.html'
    success_url = reverse_lazy('index')


class PhotoDetailView(View):

    def get(self, request, pk):
        photo = Photo.objects.get(pk=pk)
        comments = photo.comment_set.order_by('date')
        form = AddCommentForm()
        ctx = {'form': form,
               'photo': photo,
               'comments': comments}
        return TemplateResponse(request, 'photoalbum/photo_detail.html', ctx)

    def post(self, request, pk):
        form = AddCommentForm(request.POST)
        ctx = {'form': form}
        if form.is_valid():
            comment = form.cleaned_data['content']
            Comment.objects.create(content=comment,
                                   user=request.user,
                                   photo_id=pk)
            return redirect('photo_detail', pk=pk)
        return TemplateResponse(request, 'photoalbum/photo_detail.html', ctx)


class MyProfileView(View):

    def get(self, request):
        user = request.user
        photos = user.photo_set.all()
        return TemplateResponse(request,
                                'photoalbum/profile.html',
                                {'photos': photos})


class PhotoUpdateView(View):

    def get(self, request, pk):
        photo = Photo.objects.get(id=pk)
        form = PhotoUpdateForm(instance=photo)
        return TemplateResponse(request,
                                'photoalbum/photo_update.html',
                                {'form': form, 'photo': photo})

    def post(self, request, pk):
        photo = Photo.objects.get(id=pk)
        form = PhotoUpdateForm(request.POST, request.FILES, instance=photo)
        ctx = {'form': form}
        if form.is_valid():
            form.save()
            return redirect('profile')
        return TemplateResponse(request, 'photoalbum/photo_update.html', ctx)


class ResetPasswordView(PermissionRequiredMixin, View):
    permission_required = 'auth.change_user'

    def get(self, request, id):
        form = ResetPasswordForm()
        user = User.objects.get(id=id)
        return TemplateResponse(request,
                                'photoalbum/reset_password.html',
                                {'form': form, 'user': user})

    def post(self, request, id):
        form = ResetPasswordForm(request.POST)
        user = User.objects.get(id=id)
        ctx = {'form': form, 'user': user}
        if form.is_valid():
            new_pass = form.cleaned_data['new_pass']
            user.set_password(new_pass)
            user.save()
            logout(request)
            ctx.update({'message': """
            Hasło zostało zmienione, zaloguj się ponownie.
            """
                        })
        else:
            ctx.update({'message': 'Błędne dane w formularzu'})
        return TemplateResponse(request, 'photoalbum/reset_password.html', ctx)


def like_photo(request):
    if request.method == 'POST':
        photo_id = request.POST['photo_id']
        is_liked = request.POST['is_liked']
        liked_photo = Photo.objects.get(id=photo_id)
        if is_liked == 'true':
            like = Like.objects.filter(photo=liked_photo, user=request.user)[0]
            like.delete()
        else:
            Like.objects.create(photo=liked_photo, user=request.user)
        count_likes = Like.objects.filter(photo_id=photo_id)
        count_likes = len(count_likes)
        to_dump = dict()
        to_dump['count_likes'] = count_likes

        return HttpResponse(json.dumps(to_dump))
    return HttpResponse("Invalid method")


class CommentDeleteView(DeleteView):
    model = Comment
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('photo_detail')

    def get_success_url(self):
        return reverse('photo_detail', kwargs={'pk': self.object.photo.id})


class ModelFormWidgetMixin(object):
    def get_form_class(self):
        return modelform_factory(self.model,
                                 fields=self.fields,
                                 widgets=self.widgets)


class CommentUpdateView(ModelFormWidgetMixin, UpdateView):
    model = Comment
    fields = ['content']
    widgets = {'content': forms.Textarea(attrs={'cols': 40, 'rows': 3})}
    template_name_suffix = '_update_form'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('photo_detail')

    def get_success_url(self):
        return reverse('photo_detail', kwargs={'pk': self.object.photo.id})

photoalbum/templates/photoalbum/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../static/style/style.css">

    <title>Photo Album</title>
  </head>
  <body>

  <header>
    Dzisiaj jest: {{ date|date:'d.m.Y'}} <br>

    {% if request.user.is_authenticated %}
        Witaj {{ request.user.username }} <a href="{% url 'logout' %}">Wyloguj</a>
        <a href="{% url 'add_photo' %}">Dodaj zdjęcie</a>
        <a href="{% url 'profile' %}">Mój profil</a>
    {% else %}
        <a href="{% url 'register' %}">Zarejestruj się</a>
    {% endif %}

    <h1>Photo Album</h1>

</header>
{% block content %}

{% endblock %}


    <script src="../../static/jquery/jquery-3.3.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="../../static/js/index.js"></script>

  </body>
</html>

photoalbum/templates/photoalbum/comment_confirm_delete.html
{% extends 'photoalbum/base.html' %}
{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    Czy na pewno usunąć ten komentarz?
    <input type="submit" value="Usuń">
</form>
<br>
<a href="{% url 'photo_detail' pk=comment.photo_id %}">Powrót</a>
{% endblock %}

photoalbum/templates/photoalbum/comment_update_form.html
{% extends 'photoalbum/base.html' %}

{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="zapisz zmiany">
</form>
    <br>
    <a href="{% url 'photo_detail' pk=comment.photo_id %}">Powrót</a>

{% endblock %}

photoalbum/templates/photoalbum/index.html
{% extends 'photoalbum/base.html' %}

{% block content %}
    {% if request.user.is_authenticated  %}
        {% csrf_token %}
        <div class="album py-5">
            <div class="container">
                <div class="row">
                    {% for photo in photos %}
                        <div class="col-md-4">
                        {% load thumbnail %}
                            <a href="{% url 'photo_detail' pk=photo.id %}"><img src="{{photo.path|thumbnail_url:'thumb' }}" class="img-fluid"></a><br>
                            <a href="#" class="like_button" data-photo="{{ photo.id }}">Lubię To!</a>
                            {% if photo.id in likes %}
                                <span class="like_span liked">Polubiłeś to zdjęcie!</span>
                            {% else %}
                                <span class="like_span"></span>
                            {% endif %}
                        <p>Liczba polubień:
                            <span>{{ photo.like_set.all|length }}</span>
                            <br>
                            Komentarze:
                            <a>{{ photo.comment_set.all|length }}</a> {# <a> as substitute for <span> works as well #}
                        </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

photoalbum/templates/photoalbum/login.html
{% extends 'photoalbum/base.html' %}

{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="zaloguj">
</form>
<p>{{ message }}</p>
{% endblock %}

photoalbum/templates/photoalbum/photo_confirm_delete.html
{% extends 'photoalbum/base.html' %}
{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    Czy na pewno usunąć zdjęcie?
    <input type="submit" value="Usuń">
</form>
<br>
<a href="{% url 'profile' %}">Powrót</a>
{% endblock %}

photoalbum/templates/photoalbum/photo_detail.html
{% extends 'photoalbum/base.html' %}

{% block content %}
  <h3>{{ photo.title }}</h3>
    <p><img src="{{ photo.path.url }}"></p>
{#        <img src="{{ MEDIA_URL }}/{{ photo.path }}">#}
    <p><b>Autor:</b> {{ photo.user }}</p>
    <h3>Komentarze:</h3>
    <ol>
    {% for comment in comments %}
        <li>
            <h4>{{ comment.user }}:</h4>
            <h5>{{ comment.date|date:"d.m.Y H:i"}}</h5>
            {{ comment.content }}
            <br>
        {% if comment.user == request.user %}
                <a href="{% url 'delete_comment' pk=comment.id %}">Usuń</a>
                <a href="{% url 'update_comment' pk=comment.id %}">Edytuj</a>
            {% endif %}
        </li>
        <br>
    {% endfor %}
    </ol>
    <form action="#" method="post">
    <fieldset>
        <legend>Podziel się swoją opinią</legend>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="wyślij">
    </fieldset>
</form>
    <br>

    <a href="{% url 'index' %}">Powrót</a>

{% endblock %}

photoalbum/templates/photoalbum/photo_form.html
{% extends 'photoalbum/base.html' %}

{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="dodaj zdjęcie">
</form>
{% endblock %}

photoalbum/templates/photoalbum/photo_update.html
{% extends 'photoalbum/base.html' %}

{% block content %}
<form action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="zapisz zmiany">
</form>
    <br>
    <a href="{% url 'profile' %}">Powrót</a>

{% endblock %}

photoalbum/templates/photoalbum/profile.html
{% extends 'photoalbum/base.html' %}

{% block content %}
    <hr>
    <h5>Profil {{ request.user }}</h5><br>
<fieldset>
    <label>Zarządzanie kontem:</label>
    <span> <a href="{% url 'reset_password' id=request.user.id %}">Zmień hasło</a></span>
    <span><a href="{% url 'delete_user' pk=request.user.id %}">Usuń konto</a></span>
</fieldset>
    <br>
    <hr>
    <h2>Moje zdjęcia:</h2>
    {% for photo in photos %}
        <h4>{{ photo.title }}</h4>
        <p><img src="{{ photo.path.url }}"></p>
        <a href="{% url 'delete_photo' pk=photo.id %}">Usuń</a>
        <a href="{% url 'update_photo' pk=photo.id %}">Edytuj</a><br><br>
    {% empty %}
        <p>Brak zdjęć</p>
    {% endfor %}

    <a href="{% url 'index' %}">Powrót</a>
{% endblock %}

photoalbum/templates/photoalbum/reset_password.html
{% extends 'photoalbum/base.html' %}

{% block content %}
    <form action="{% url 'reset_password' user.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="zmień hasło">
</form>
<p>{{ message }}</p>

{% endblock %}

photoalbum/templates/photoalbum/user_confirm_delete.html
{% extends 'photoalbum/base.html' %}
{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    Czy na pewno usunąć konto?
    <input type="submit" value="Usuń">
</form>
{% endblock %}

photoalbum/templates/photoalbum/user_form.html
{% extends 'photoalbum/base.html' %}

{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="zarejestruj się">
</form>
<p>{{ message }}</p>
{% endblock %}